install:
	test -d ./node_modules/md2gslides/bin/ || npm install md2gslides
	test -d venv || virtualenv venv
	venv/bin/pip install -Ur requirements.txt

buildstatus: install
	venv/bin/python finishline \
		--config ${YOUR_CONFIG_FILE} > foo.md

uploadstatus: buildstatus
	./node_modules/md2gslides/bin/md2gslides.js foo.md \
		-t "${YOUR_SLIDES_TITLE}" \
		-e -a $(SLIDES_ID)

buildemail: install
	venv/bin/python finishline \
		--config ${YOUR_CONFIG_FILE} > report-$(shell date '+%F').md
