install:
	test -d ./node_modules/md2gslides/bin/ || npm install md2gslides
	test -d venv || virtualenv venv
	venv/bin/pip install -Ur requirements.txt

buildstatus: install
	venv/bin/python finishline \
		--scenario statusslides \
		--config cpcollab.conf > foo.md

uploadstatus: buildstatus
	./node_modules/md2gslides/bin/md2gslides.js foo.md \
		-t "DevOps Cross-pillar Collaboration Status" \
		-e -a 15bXAWuHOQiy4nTfTvztfVgXrO6vHL9XuVuP_4YKjEBo
